// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_hexpert = "CgkI0v_SjvEEEAIQBA"; // <GPGSID>
        public const string achievement_20_and_0 = "CgkI0v_SjvEEEAIQBQ"; // <GPGSID>
        public const string achievement_ten_and_0 = "CgkI0v_SjvEEEAIQAw"; // <GPGSID>
        public const string leaderboard_world_rankings = "CgkI0v_SjvEEEAIQAg"; // <GPGSID>
        public const string achievement_color_king = "CgkI0v_SjvEEEAIQBg"; // <GPGSID>
        public const string achievement_hexcelence = "CgkI0v_SjvEEEAIQAQ"; // <GPGSID>

}

